### ISSUE TITLE
I can't figure out how to use Feature Flag to make thirtyfour work correctly.

### ISSUE THREAD

**Issue by steadylearner** [stevepryde/thirtyfour#11]
Hi, I am back to test your project again and I think that the API have changed a lot especially using a feature flag to use async-std, tokio, sync etc.

I keep having the project work at runtime because I am not sure how I can configure features flags to use **tokio and async** feature in [Cargo.toml](https://github.com/steadylearner/Rust-Full-Stack/blob/master/selenium/login/Cargo.toml)

```toml
[package]
name = "login"
version = "0.1.0"
authors = ["www.steadylearner.com/blog/search/Rust"]
edition = "2018"

[dependencies]
tokio = "0.2.21"

# https://doc.rust-lang.org/cargo/reference/features.html#the-features-section
# https://github.com/stevepryde/thirtyfour#feature-flags
# https://rust-random.github.io/book/features.html

[dependencies.thirtyfour]
version = "0.12.0"
default-features = false
features = ["tokio-runtime"]
```

It is currently working with **$cago c** with the [main.rs](https://github.com/steadylearner/Rust-Full-Stack/blob/master/selenium/login/src/main.rs) but when I use **$cargo run** it shows the error below and I think that it is from Cargo.toml file.

```
Error: ReqwestError(reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) })
[Finished running. Exit status: 1]
```

Can you share the fully working example? I just need to visit that I can visit the reddit website with your project.

p.s It is difficult to what I need to do to make feature flags work correctly. Would you include them at separate folders or README.md at your project?

It will be better for beginners like myself to use your project better.

I want to commit the Reddit login example to your project so please help me to get through this.
